---------------------------------------------------
--프로젝트
--등급별 할인율

CREATE TABLE GRADESALE
(사용자등급 VARCHAR2(15) CONSTRAINT GRADESALE_GRADE_PK PRIMARY KEY,
이용횟수 NUMBER(4), 할인율 NUMBER(15));

CREATE TABLE USERINFO
(ID VARCHAR2(10) CONSTRAINT USERINFO_ID_PK PRIMARY KEY,
사용자이름 VARCHAR2(10) NOT NULL, 나이 NUMBER(3) NOT NULL,
성별 VARCHAR2(6) NOT NULL, PW VARCHAR2(12) NOT NULL,
주소 VARCHAR2(40), 상세주소 VARCHAR2(15),
사용자등급 VARCHAR2(10) DEFAULT '노말' CONSTRAINT USERINFO_GRADE_FK REFERENCES GRADESALE(사용자등급));

CREATE TABLE ROOM
(호수 NUMBER(4) CONSTRAINT ROOM_호수_PK PRIMARY KEY, 객실등급 VARCHAR2(15), 오션뷰 VARCHAR2(2),
노래방 VARCHAR2(2), 욕조여부 VARCHAR2(2), 금액 NUMBER(6) NOT NULL, 이용인원 NUMBER(2));

CREATE TABLE RESERVE
(호수 NUMBER(4) CONSTRAINT RESERVE_호수_PK PRIMARY KEY,
ID VARCHAR2(10) CONSTRAINT RESERVE_ID_FK REFERENCES USERINFO(ID) ON DELETE CASCADE,
입실시간 DATE, 퇴실시간 DATE, 총금액 NUMBER(7));

CREATE TABLE DETAIL
(NO NUMBER(5) CONSTRAINT DETAIL_NO_PK PRIMARY KEY,
ID VARCHAR2(10) CONSTRAINT DETAIL_ID_FK REFERENCES USERINFO(ID),
호수 NUMBER(4) CONSTRAINT DETAIL_호수_FK REFERENCES ROOM(호수),
입실날짜 DATE, 퇴실날짜 DATE, 금액 NUMBER(6));

CREATE TABLE COUNTGRADE
(ID VARCHAR2(10) CONSTRAINT COUNTGRADE_ID_FK
REFERENCES USERINFO(ID) ON DELETE CASCADE,
CNT NUMBER(5));



CREATE OR REPLACE TRIGGER GRADEUP
AFTER INSERT ON RESERVE
FOR EACH ROW
DECLARE v_cnt NUMBER;
BEGIN SELECT CNT INTO V_CNT FROM COUNTGRADE WHERE ID = :NEW.ID;
UPDATE COUNTGRADE SET CNT = v_cnt + 1 WHERE ID = :NEW.ID;
    IF v_cnt +1 >= 15 THEN
        UPDATE USERINFO SET 사용자등급 = '플레티넘' WHERE ID = :NEW.ID;
    ELSIF v_cnt +1 >= 12 THEN
        UPDATE USERINFO SET 사용자등급 = '다이아' WHERE ID = :NEW.ID;
    ELSIF v_cnt +1 >= 9 THEN
        UPDATE USERINFO SET 사용자등급 = '골드' WHERE ID = :NEW.ID;
    ELSIF v_cnt +1 >= 7 THEN
        UPDATE USERINFO SET 사용자등급 = '실버' WHERE ID = :NEW.ID;
    ELSIF v_cnt + 1 >= 5 THEN
        UPDATE USERINFO SET 사용자등급 = '브론즈' WHERE ID = :NEW.ID;
    END IF;
END;

CREATE OR REPLACE TRIGGER GRADESET
AFTER INSERT ON USERINFO
FOR EACH ROW
BEGIN INSERT INTO COUNTGRADE (ID,CNT)
VALUES (:NEW.ID,0);
END;

drop table USERINFO;
drop table RESERVE;
drop table ROOM;
drop table DETAIL;
drop table GRADESALE;
drop table COUNTGRADE;



select * from countgrade;

SELECT * from USERINFO;

commit;


DROP TRIGGER GRADEDEL;



select * from countgrade;

PURGE RECYCLEBIN;

--sqlplus

commit;
DESC ROOM;
DESC GRADESALE;
DESC USERINFO;
DESC RESERVE;
DESC DETAIL;

select * from countgrade;

SELECT * FROM USER_CONSTRAINTS;

--호수, 등급, 오션뷰, 노래방, 욕조, 금액, 인원
INSERT INTO ROOM VALUES (101, '스탠다드', 'O', 'X', 'O', 40000, 2);
INSERT INTO ROOM VALUES (102, '스탠다드', 'O', 'X', 'O', 40000, 2);
INSERT INTO ROOM VALUES (103, '스탠다드', 'X', 'X', 'X', 36000, 2);
INSERT INTO ROOM VALUES (104, '스탠다드', 'O', 'X', 'X', 38000, 2);
INSERT INTO ROOM VALUES (105, '스탠다드', 'X', 'X', 'X', 36000, 2);
INSERT INTO ROOM VALUES (201, '디럭스', 'O', 'X', 'X', 42000, 3);
INSERT INTO ROOM VALUES (202, '디럭스', 'O', 'X', 'X', 42000, 3);
INSERT INTO ROOM VALUES (203, '디럭스', 'X', 'O', 'O', 45000, 3);
INSERT INTO ROOM VALUES (204, '디럭스', 'O', 'X', 'O', 45000, 3);
INSERT INTO ROOM VALUES (205, '디럭스', 'O', 'O', 'O', 48000, 3);
INSERT INTO ROOM VALUES (301, '럭셔리', 'O', 'X', 'O', 52000, 4);
INSERT INTO ROOM VALUES (302, '럭셔리', 'O', 'X', 'O', 52000, 4);
INSERT INTO ROOM VALUES (303, '럭셔리', 'X', 'X', 'O', 50000, 4);
INSERT INTO ROOM VALUES (304, '럭셔리', 'O', 'X', 'O', 52000, 4);
INSERT INTO ROOM VALUES (305, '럭셔리', 'O', 'O', 'O', 55000, 4);
INSERT INTO ROOM VALUES (501, '파티룸', 'O', 'O', 'O', 70000, 6);
INSERT INTO ROOM VALUES (502, '파티룸', 'O', 'O', 'O', 70000, 6);
INSERT INTO ROOM VALUES (503, '파티룸', 'X', 'O', 'O', 68000, 6);
INSERT INTO ROOM VALUES (504, '파티룸', 'O', 'O', 'O', 70000, 6);
INSERT INTO ROOM VALUES (505, '파티룸', 'X', 'O', 'O', 68000, 6);

--등급, 횟수, 할인률
INSERT INTO GRADESALE VALUES ('노말', 0, 0);
INSERT INTO GRADESALE VALUES ('브론즈', 5, 3000);
INSERT INTO GRADESALE VALUES ('실버', 7, 6000);
INSERT INTO GRADESALE VALUES ('골드', 9, 8000);
INSERT INTO GRADESALE VALUES ('다이아', 12, 10000);
INSERT INTO GRADESALE VALUES ('플레티넘', 15, 12000);

commit;

