--연습계정

select * FROM TAB;

SELECT * FROM CUSTOM;

SELECT USERID,USERNAME,ADDR1,SUBSTR(JUMIN,1,6) BIRTH FROM CUSTOM WHERE ADDR1 = '서울특별시';

SELECT USERID,USERNAME,ADDR1,SUBSTR(JUMIN,1,6) BIRTH FROM CUSTOM WHERE ADDR1 LIKE '경기%';


SELECT * FROM CUSTOM; --고객정보
SELECT * FROM COMPANY; -- 회사정보
SELECT * FROM POINT; --포인트
SELECT * FROM PRODUCT; --판매제품
SELECT * FROM RESEARCH; --설문조사
SELECT * FROM SALES; --판매내역

SELECT * FROM CUSTOM;
SELECT CONCAT(SUBSTR(JUMIN,1,8),'******') JUMIN FROM CUSTOM;
SELECT RPAD(SUBSTR(JUMIN,1,8),14,'*') JUMIN FROM CUSTOM;
SELECT RPAD(JUMIN,8) JUMIN FROM CUSTOM;










