--SESTEM

CREATE USER oracle_prac 
IDENTIFIED BY prac 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

DROP USER LEE CASCADE; --계정삭제

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO oracle_prac; 


SELECT * FROM DBA_USERS;

--UNUSED 확인
SELECT * FROM DBA_UNUSED_COL_TABS;

------------------------------------------------------------------------

--DCL(DATA CONTROL LANGUAGE)
--GRANT : USER나 OBJECT에 권한을 부여
--REVOKE : USER나 OBJECT에 권한을 회수

--권한의 종류
--SYSTEM 권한 : DATABASE OBJECT들을 생성,수정,삭제 할수있는 권한, DBA가 USERS한테 줌
--OBJECT 권한 : OBJECT 내용을 조작(INSERT,UPDATE,DELETE,SELECT) 할수있는 권한, USER가 다른USERS들한테 줌

CREATE USER TEST
IDENTIFIED BY A123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;


--시스템권한들
SELECT * FROM SYSTEM_PRIVILEGE_MAP;

--내 권한들
SELECT * FROM USER_TAB_PRIVS_MADE;

--권한 부여
GRANT CREATE SESSION TO TEST;

GRANT CREATE TABLE TO TEST;

GRANT UNLIMITED TABLESPACE TO TEST;

--GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO TEST;
--REVOKE CONNECT,RESOURCE,UNLIMITED TABLESPACE FROM TEST;

--PUBLIC으로 주면 모든 유저들한테 줌, 회수할때도 PUBLIC으로 뺏음
--GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO PUBLIC;
--REVOKE CONNECT,RESOURCE,UNLIMITED TABLESPACE FROM PUBLIC;

--권한 뺏기
REVOKE UNLIMITED TABLESPACE FROM TEST;

REVOKE CREATE TABLE FROM TEST;

REVOKE CONNECT FROM TEST;
 
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO TEST;

--ROLE
SELECT * FROM USER_ROLE_PRIVS;

GRANT CREATE ROLE TO KIM;

--ROLE 만듬
CREATE ROLE MANAGER;
--MANAGER ROLE에 권한 두개 넣음
GRANT CREATE TABLE,CREATE VIEW TO MANAGER;
--ROLE 확인
SELECT * FROM DBA_ROLES;
--KIM한테 줌
GRANT MANAGER TO KIM;

GRANT CREATE VIEW TO KIM;

--DICTIONARY
SELECT * FROM DICTIONARY;
SELECT COUNT(*) FROM DICTIONARY;

SELECT * FROM DBA_CONSTRAINTS;

SELECT * FROM DBA_USERS;

SELECT * FROM USER_PROCEDURES;

GRANT CREATE SYNONYM TO KIM;

grant create procedure to suzi;

--다른컴과 db연결
--클라이언트만
--다른 db갈수있는 링크 만들수 있는 권한 부여
GRANT CREATE DATABASE LINK TO suzi;


CREATE USER pj
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO pj; 